name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ../
    - name: Run tests
      run: |
        python -m unittest discover 
